from django.conf.urls import url
from team import views

urlpatterns = [
    url(r'^$', views.test, name='index'),
    url(r'^valid_code/$', views.valid_code),
    url(r'^test/$', views.test),
    url(r'^search/$', views.search),
    url(r'^hot_product/$', views.hot_product),
    url(r'^hot_team/$', views.hot_team),
    url(r'^search_job/$', views.search_job),
    url(r'^add_job/$', views.add_job),
    url(r'^update_job/$', views.update_job),
    url(r'^delete_job/$', views.delete_job),
    url(r'^job_type/$', views.job_type),
    url(r'^product/save_img/$', views.save_prod_img),
    url(r'^product/insert/$', views.add_product),
    url(r'^product/update/$', views.update_product),
    url(r'^product/delete/$', views.delete_product),
    url(r'^product/info/$', views.info_product),
    url(r'^product/search/$', views.search_product),
    url(r'^register/$', views.register),
    url(r'^login/$', views.login),
    url(r'^reset/$', views.reset),
    url(r'^fetch/$', views.fetch),
    url(r'^update_pwd/$', views.update_pwd),
    url(r'^job_info/$', views.job_info),
    url(r'^info/$', views.info),
    url(r'^invite/$', views.invite),
    url(r'^update_team_info/$', views.update_team_info),
    url(r'^upload_logo/$', views.upload_logo),
    url(r'^add_team_label/$', views.add_team_label),
    url(r'^rm_team_label/$', views.rm_team_label),
    url(r'^rm_team_stu/$', views.rm_team_stu),
    url(r'^add_team_stu/$', views.add_team_stu),
    url(r'^add_team_photo/$', views.add_team_photo),
    url(r'^rm_team_photo/$', views.rm_team_photo),
    url(r'^update_team_contact/$', views.update_team_contact),
    url(r'^business/$', views.business),
    url(r'^name2mail/$', views.name2mail),
    url(r'^invite_stu/$', views.invite_stu),
    url(r'^apply/list/$', views.get_apply_list),
    url(r'^apply/info/$', views.get_apply_info),
    url(r'^apply/mail/$', views.apply_mail),
    url(r'^apply/handle/$', views.apply_handle),
    url(r'^all/newest$', views.newest),
    url(r'^team/newest$', views.newest_teams),
]