PRODUCT_SUCCEED = '0'
SUCCEED = '0'

ERR_PROD_TABLE = '-101'
MSG_PROD_TABLE = '数据库操作失败'

ERR_PROD_NOT_EXIT = '-102'
MSG_PROD_NOT_EXIT = '项目不存在'

ERR_PROD_SAVE_IMG = '-103'
MSG_PROD_SAVE_IMG = '项目照片保存失败'

ERR_PROD_CHECK_IMG = '-104'
MSG_PROD_CHECK_IMG = '项目照片格式错误'

ERR_JOB_NOT_EXIT = '-122'
MSG_JOB_NOT_EXIT = '职位不存在'