# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('j_type', models.IntegerField(default=0)),
                ('w_type', models.IntegerField(default=0)),
                ('min_salary', models.FloatField(default=0.0)),
                ('max_salary', models.FloatField(default=0.0)),
                ('prince', models.IntegerField(default=0)),
                ('city', models.IntegerField(default=0)),
                ('town', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=100)),
                ('exp_cmd', models.CharField(default='', max_length=100)),
                ('summary', models.CharField(default='', max_length=100)),
                ('job_cmd', models.CharField(default='', max_length=600)),
                ('work_cmd', models.CharField(default='', max_length=600)),
                ('pub_state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('content', models.CharField(default='', max_length=600)),
                ('img_path', models.CharField(default='', max_length=200)),
                ('reward', models.CharField(default='', max_length=600)),
                ('last_visit_cnt', models.IntegerField(default=0)),
                ('week_visit_cnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pwd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd_hash', models.CharField(default='', max_length=100)),
                ('invite_code', models.CharField(default='', max_length=20)),
                ('reset_key', models.CharField(default='', max_length=100)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('logo_path', models.CharField(default='', max_length=200)),
                ('contact_tel', models.CharField(default='', max_length=20)),
                ('contact_mail', models.CharField(default='', max_length=40)),
                ('slogan', models.CharField(default='', max_length=100)),
                ('about', models.CharField(default='', max_length=600)),
                ('history', models.CharField(default='', max_length=600)),
                ('b_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=200)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StuInfo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pwd',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t2pwd', to='team.Team'),
        ),
        migrations.AddField(
            model_name='product',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AddField(
            model_name='label',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AddField(
            model_name='job',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
