# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='content',
        ),
        migrations.RemoveField(
            model_name='job',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='job',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='team',
            name='strength',
        ),
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='exp_cmd',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='j_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='job_cmd',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='job',
            name='max_salary',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='job',
            name='prince',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='pub_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='summary',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='town',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='w_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='work_cmd',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='product',
            name='img_path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='last_visit_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='reward',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='product',
            name='week_visit_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='b_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='history',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='slogan',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='team',
            name='about',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='team',
            name='contact_mail',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='team',
            name='contact_tel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='teamimg',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AddField(
            model_name='label',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
