# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20160710_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pwd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd_hash', models.CharField(default='', max_length=100)),
                ('invite_code', models.CharField(default='', max_length=20)),
                ('state', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
            preserve_default=False,
        ),
    ]
