CREATE DATABASE wemeet;
insert into team_jobtype (name) values ('行政');
insert into team_jobtype (name) values ('产品');
insert into team_jobtype (name) values ('技术');
insert into team_jobtype (name) values ('设计');
insert into team_jobtype (name) values ('运营');
insert into team_jobtype (name) values ('运维支持');
insert into team_jobtype (name) values ('市场');
insert into team_jobtype (name) values ('文案策划');
insert into team_jobtype (name) values ('营销');

ALTER TABLE auth_group CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE auth_group_permissions CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE auth_permission CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE auth_user CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE auth_user_groups CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE auth_user_user_permissions CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE django_admin_log CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE django_content_type CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE django_migrations CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE django_session CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE job_apply CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE stu_account CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE stu_edu CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE stu_info CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE stu_intern CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE stu_intern CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE stu_proj CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE stu_skill CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE stu_works CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE team_businesstype CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE team_job CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE team_jobtype CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE team_label CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE team_product CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE team_pwd CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE team_team CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE team_teamimg CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE team_teamstu CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE team_teamtype CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE team_worktype CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
