OK_REG = 1
REG_FAIL_EXIST = -1
REG_FAIL_DB = -2

OK_ACTIVATE = 3
ERR_ACTIVATE_NOTEXIST = -3
ERR_ACTIVATE_DB = -4

OK_LOGIN = 5
ERR_LOGIN_NOTEXIST = -5  # 账号不存在
ERR_LOGIN_DB = -6
ERR_LOGIN_WRONG_PWD = -7
ERR_LOGIN_NONACTIVATED = -8  # 账号未激活

OK_RESET_MAIL = 9
ERR_RESET_MAIL_NOTEXIST = -9
ERR_RESET_MAIL_DB = -10

ERR_RESET_NOTEXIST = -11
ERR_RESET_DB = -12
ERR_RESET_OUT_DATE = -13

OK_CHANGE_PWD = 14
ERR_CHANGE_PWD_NOTEXIST = -14  # 账号不存在
ERR_CHANGE_PWD_WRONG_CREDENTIAL = -15  # 凭据错误
ERR_CHANGE_PWD_DB = -16

OK_GET_INFO = 17  # 获取学生信息
ERR_GET_INFO_NOTEXIST = -17  # 获取学生信息
ERR_GET_INFO_DB = -18  # 获取学生信息

OK_UPDATE_STU_INFO = 19  # 更新学生信息
ERR_UPDATE_STU_INFO_DB = -19  # 更新学生信息失败

OK_SAVE_AVATAR = 20
ERR_AVATAR_FILE_INVALID = -20
ERR_SAVE_AVATAR_FAIL = -21

OK_SAVE_RESUME = 22
ERR_RESUME_FILE_INVALID = -22
ERR_SAVE_RESUME_FAIL = -23

OK_APPLY = 24
ERR_APPLY_DB = -24
ERR_APPLY_NO_RESUME = -25
ERR_APPLY_EXIST = -26

OK_ADD_EDU = 27
ERR_ADD_EDU_FULL = -27
ERR_ADD_EDU_DB = -28

OK_GET_EDU = 29
ERR_GET_NO_EDU = -29
ERR_GET_EDU_DB = -30

OK_GET_INTERN = 31
ERR_GET_NO_INTERN = -31
ERR_GET_INTERN_DB = -32

OK_GET_PROJ = 31
ERR_GET_NO_PROJ = -31
ERR_GET_PROJ_DB = -32

OK_GET_WORKS = 33
ERR_GET_NO_WORKS = -33
ERR_GET_WORKS_DB = -34

OK_GET_SKILL = 35
ERR_GET_NO_SKILL = -35
ERR_GET_SKILL_DB = -36

OK_UPDATE_EDU = 37
ERR_UPDATE_EDU_DB = -37

OK_DEL_EDU = 38
ERR_DEL_EDU_DB = -38

OK_ADD_INTERN = 39
ERR_ADD_INTERN_FULL = -39
ERR_ADD_INTERN_DB = -40

OK_UPDATE_INTERN = 41
ERR_UPDATE_INTERN_DB = -41

OK_DEL_INTERN = 42
ERR_DEL_INTERN_DB = -42

OK_ADD_PROJ = 43
ERR_ADD_PROJ_FULL = -43
ERR_ADD_PROJ_DB = -44

OK_UPDATE_PROJ = 45
ERR_UPDATE_PROJ_DB = -45

OK_DEL_PROJ = 46
ERR_DEL_PROJ_DB = -46

OK_ADD_SKILL = 47
ERR_ADD_SKILL_FULL = -47
ERR_ADD_SKILL_DB = -48

OK_UPDATE_SKILL = 49
ERR_UPDATE_SKILL_DB = -49

OK_DEL_SKILL = 50
ERR_DEL_SKILL_DB = -50

OK_SAVE_WORKS = 51
ERR_WORKS_FILE_INVALID = -51
ERR_SAVE_WORKS_FAIL = -52

OK_ADD_WORKS = 53
ERR_ADD_WORKS_EXIST = -53
ERR_ADD_WORKS_DB = -54

OK_UPDATE_WORKS = 50
ERR_UPDATE_WORKS_DB = -50

OK_DEL_WORKS = 51
ERR_DEL_WORKS_DB = -51

OK_GET_RESUME = 52
ERR_GET_NO_RESUME = -52
ERR_GET_RESUME_DB = -53











