# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-09 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('team_id', models.CharField(max_length=45)),
                ('resume_type', models.IntegerField()),
            ],
            options={
                'db_table': 'job_apply',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('resume_edu', models.CharField(blank=True, max_length=600, null=True)),
                ('resume_internship', models.CharField(blank=True, max_length=1000, null=True)),
                ('resume_project', models.CharField(blank=True, max_length=1000, null=True)),
                ('resume_stu_work', models.CharField(blank=True, max_length=600, null=True)),
                ('resume_award', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'resume',
            },
        ),
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('school', models.CharField(blank=True, max_length=45, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('mail', models.CharField(blank=True, max_length=45, null=True)),
                ('avatar_path', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'stu_info',
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.StuInfo'),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.Resume'),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.StuInfo'),
        ),
    ]
