# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('stu_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('psw', models.CharField(max_length=32)),
                ('stu_name', models.CharField(blank=True, max_length=20, null=True)),
                ('stu_school', models.CharField(blank=True, max_length=45, null=True)),
                ('stu_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('stu_mail', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'stu_info',
            },
        ),
        migrations.CreateModel(
            name='StuJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=45)),
                ('stu_job_state', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'stu_job',
            },
        ),
        migrations.CreateModel(
            name='StuResume',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('resume_edu', models.CharField(blank=True, max_length=600, null=True)),
                ('resume_internship', models.CharField(blank=True, max_length=1000, null=True)),
                ('resume_project', models.CharField(blank=True, max_length=1000, null=True)),
                ('resume_stu_work', models.CharField(blank=True, max_length=600, null=True)),
                ('resume_award', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'stu_resume',
            },
        ),
    ]
