# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('resume_type', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'job_apply',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resume_edu', models.CharField(blank=True, max_length=600, null=True)),
                ('resume_internship', models.CharField(blank=True, max_length=600, null=True)),
                ('resume_project', models.CharField(blank=True, max_length=600, null=True)),
                ('resume_stu_work', models.CharField(blank=True, max_length=600, null=True)),
                ('resume_award', models.CharField(blank=True, max_length=600, null=True)),
                ('file_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'resume',
            },
        ),
        migrations.CreateModel(
            name='StuAccount',
            fields=[
                ('account', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=100)),
                ('is_activated', models.BooleanField(default=False)),
                ('ciphertext', models.CharField(max_length=600, null=True)),
                ('reset_date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'stu_account',
            },
        ),
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('school', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tel', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('mail', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('avatar_path', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('edu_background', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('grade', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('major', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'db_table': 'stu_info',
            },
        ),
        migrations.AddField(
            model_name='stuaccount',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StuInfo'),
        ),
        migrations.AddField(
            model_name='resume',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.StuInfo'),
        ),
    ]
