# Tag for DAL
OK_INSERT = 1
ERR_INSERT_DB = -1

OK_DELETE = 2
ERR_DELETE_NOTEXIST = -2  # 删除
ERR_DELETE_DB = -3

OK_UPDATE = 4
ERR_UPDATE_NOTEXIST = -4
ERR_UPDATE_DB = -5

OK_SELECT = 6
ERR_SELECT_NOTEXIST = -6
ERR_SELECT_DB = -7
