GOOD_REGISTER = 1
ERROR_REGISTER = -1

GOOD_CHANGE_PWD = 2
ERROR_CHANGE_PWD = -2

GOOD_UPDATE_INFO = 3
ERROR_UPDATE_INFO = -3

ERROR_GET_INFO = -4

ERROR_AVATAR_FILE_INVALID = -5
ERROR_AVATAR_SAVE_FAILED = -6
