GOOD_REGISTER = 1
ERROR_REGISTER = -1

GOOD_ACTIVATE = 2
ERROR_ACTIVATE_DOESNOTEXIST = -2

GOOD_LOGIN = 3
ERROR_LOGIN_DOESNOTEXIST = -3  # 账号不存在
ERROR_LOGIN_WRONG_PWD = -4
ERROR_LOGIN_NONACTIVATED = -5  # 账号未激活

GOOD_RESET_MAIL = 6
ERROR_RESET_MAIL_DOESNOTEXIST = -6

ERROR_RESET_DOESNOTEXIST = -7

GOOD_CHANGE_PWD = 8
ERROR_CHANGE_PWD_DOESNOTEXIST = -8  # 账号不存在
ERROR_CHANGE_PWD_WRONG_CREDENTIAL = -9  # 凭据错误

ERROR_GET_INFO_DOESNOTEXIST = -10  #获取学生

GOOD_UPDATE_INFO = 101
ERROR_UPDATE_INFO = -101


ERROR_AVATAR_FILE_INVALID = -103
ERROR_AVATAR_SAVE_FAILED = -104




