OK_REG = 1
REG_FAIL_EXIST = -1
REG_FAIL_DB = -108

OK_ACTIVATE = 2
ERR_ACTIVATE_NOTEXIST = -2
ERR_ACTIVATE_DB = -105

OK_LOGIN = 3
ERR_LOGIN_NOTEXIST = -3  # 账号不存在
ERR_LOGIN_DB = -106
ERR_LOGIN_WRONG_PWD = -4
ERR_LOGIN_NONACTIVATED = -5  # 账号未激活

OK_RESET_MAIL = 6
ERR_RESET_MAIL_NOTEXIST = -6
ERR_RESET_MAIL_DB = -107

ERR_RESET_NOTEXIST = -7
ERR_RESET_DB = -109
ERR_RESET_OUT_DATE = -110

OK_CHANGE_PWD = 8
ERR_CHANGE_PWD_NOTEXIST = -8  # 账号不存在
ERR_CHANGE_PWD_WRONG_CREDENTIAL = -9  # 凭据错误
ERR_CHANGE_PWD_DB = -108

ERR_GET_INFO_NOTEXIST = -10  #获取学生

OK_UPDATE_INFO = 101
ERR_UPDATE_INFO = -101


ERR_AVATAR_FILE_INVALID = -103
ERR_AVATAR_SAVE_FAILED = -104




